namespace appBienesRaices.Models
{
    public class Characteristics
    {
        public int totalSurface { get; set; }
        public int buildedSurface { get; set; }
        public int utildSurface { get; set; }
        public int landSurface { get; set; }
        public int terraceSurface { get; set; }
        public int houseSurface { get; set; }
        public int officeSurface { get; set; }
        public int warehouseSurface { get; set; }
        public int pastedSurface { get; set; }
        public int cultivatedeSurface { get; set; }
        public int administrationSurface { get; set; }
        public int plantedSurface { get; set; }
        public int hillsSurface { get; set; }
        public int hectares { get; set; }
        public int sheds { get; set; }
        public int frontMeters { get; set; }
        public int depthMeters { get; set; }
        public int showcaseMeters { get; set; }
        public int hullCoveredSurface { get; set; }
        public int height { get; set; }
        public int distanceToAsphalt { get; set; }
        public int floorStand { get; set; }
        public int density { get; set; }
        public int packing { get; set; }
        public int patronsHouse { get; set; }
        public int workersHouse { get; set; }
        public int suites { get; set; }
        public int bedrooms { get; set; }
        public int beds { get; set; }
        public int bathrooms { get; set; }
        public int livingRooms { get; set; }
        public int room { get; set; }
        public int rooms { get; set; }
        public int privates { get; set; }
        public int offices { get; set; }
        public int meetingRooms { get; set; }
        public int servicesRooms { get; set; }
        public int bedServices { get; set; }
        public int floors { get; set; }
        public int elevators { get; set; }
        public int parkings { get; set; }
        public int coveredParkings { get; set; }
        public int uncoveredParkings { get; set; }
        public int clientParkings { get; set; }
        public int apartmentsPerFloor { get; set; }
        public int officesPerFloor { get; set; }
        public int bathroomsPerFloor { get; set; }
        public int platformTrailers { get; set; }
        public int warehouses { get; set; }
        public int guests { get; set; }
        public int hullEnvironments { get; set; }
        public int towerNumber { get; set; }
        public int minimumStay { get; set; }
        public int constructionYear { get; set; }
        public int localYears { get; set; }
        public int localState { get; set; }
        public bool serviceRoom { get; set; }
        public bool serviceBathroom { get; set; }
        public bool warehouse { get; set; }
        public bool dailyDiningRoom { get; set; }
        public bool familyRoom { get; set; }
        public bool receipts { get; set; }
        public bool sauna { get; set; }
        public bool jacuzzi { get; set; }
        public bool furnished { get; set; }
        public bool petsAllowed { get; set; }
        public bool home { get; set; }
        public bool isInterior { get; set; }
        public bool regularized { get; set; }
        public bool bbq { get; set; }
        public bool tennisCourt { get; set; }
        public bool electricFence { get; set; }
        public bool cctv { get; set; }
        public bool childishGames { get; set; }
        public bool pool { get; set; }
        public bool gatePool { get; set; }
        public bool automaticGate { get; set; }
        public bool automaticWatering { get; set; }
        public bool irrigationWater { get; set; }
        public bool waterWell { get; set; }
        public bool well { get; set; }
        public bool sign { get; set; }
        public bool condominium { get; set; }
        public bool keysInOffice { get; set; }
        public bool stables { get; set; }
        public bool alarm { get; set; }
        public bool fireAlarms { get; set; }
        public bool bathroomVisit { get; set; }
        public bool kitchen { get; set; }
        public bool laundry { get; set; }
        public bool walkinCloset { get; set; }
        public bool gameRoom { get; set; }
        public bool refrigerator { get; set; }
        public bool outdoorBasketballCourt { get; set; }
        public bool indoorBasketballCourt { get; set; }
        public bool cableTv { get; set; }
        public bool gym { get; set; }
        public bool microwave { get; set; }
        public bool chimney { get; set; }
        public bool reception { get; set; }
        public bool onlyFamilies { get; set; }
        public bool hasSilo { get; set; }
        public bool hasWaterTank { get; set; }
        public bool hasWaterers { get; set; }
        public bool hasTapWater { get; set; }
        public bool hasTelephoneLine { get; set; }
        public bool wheelchairRamp { get; set; }
        public bool housekeepingService { get; set; }
        public bool ventilationSystem { get; set; }
        public bool childrenWelcome { get; set; }
        public bool hasBoiler { get; set; }
        public bool farmHouse { get; set; }
        public bool breakfastService { get; set; }
        public bool hasBascule { get; set; }
        public bool hasCutlery { get; set; }
        public bool hasDrainage { get; set; }
        public bool hasElectricGenerator { get; set; }
        public bool hasElectricLight { get; set; }
        public bool hasFarmShed { get; set; }
        public bool hasFarmyard { get; set; }
        public bool hasFittingRoom { get; set; }
        public bool hasForestation { get; set; }
        public bool hasNaturalGas { get; set; }
        public bool hasMills { get; set; }
        public bool hasLobby { get; set; }
        public bool hasGrill { get; set; }
        public bool hasDinningArea { get; set; }
        public bool hasDinningRoom { get; set; }
        public bool hasCloset { get; set; }
        public bool hasBreakfastBar { get; set; }
        public bool hasAttic { get; set; }
        public bool hasBalcony { get; set; }
        public bool hasTerrace { get; set; }
        public bool hasRoofGarden { get; set; }
        public bool hasStudy { get; set; }
        public bool hasSecurity { get; set; }
        public bool hasTv { get; set; }
        public bool hasWashingMachine { get; set; }
        public bool valetParkingService { get; set; }
        public bool hasBusinessCenter { get; set; }
        public bool hasCinemaHall { get; set; }
        public bool hasCistern { get; set; }
        public bool hasAirConditioning { get; set; }
        public bool hasCommonLaundry { get; set; }
        public bool hasGuestParking { get; set; }
        public bool hasFootballPitch { get; set; }
        public bool hasInternetAccess { get; set; }
        public bool hasPlayground { get; set; }
        public bool hasMultipurposeRoom { get; set; }
        public bool hasOpenSpaces { get; set; }
        public bool hasPaddleCourt { get; set; }
        public bool hasPartyRoom { get; set; }
        public bool hasControlledAccess { get; set; }
        public bool hasMultipleUseCourt { get; set; }
        public bool isPropertyInAuction { get; set; }
        public bool endorsementRequired { get; set; }
        public bool suitableForMortgageLoan { get; set; }
        public bool withGardener { get; set; }
        public bool withGatedCommunity { get; set; }
        public bool withGreenArea { get; set; }
        public bool withLaundryConnection { get; set; }
        public bool withSateliteTv { get; set; }
        public bool withSolarEnergy { get; set; }
        public string mall { get; set; }
        public string condUrbanization { get; set; }
        public string constructability { get; set; }
        public string equipment { get; set; }
        public string floor { get; set; }
        public string contactSchedule { get; set; }
        public string availableSince { get; set; }
        public string securityType { get; set; }
        public int floorType { get; set; }
        public int floorBedrooms { get; set; }
        public int typeFlatBathrooms { get; set; }
        public int floorKitchen { get; set; }
        public int floorDiningRoom { get; set; }
        public int floorLiving { get; set; }
        public int floorHallEntrance { get; set; }
        public int houseStyle { get; set; }
        public int houseType { get; set; }
        public int departmentType { get; set; }
        public int localtype { get; set; }
        public int propRecep { get; set; }
        public string orientation { get; set; }
        public int typeFurnitureCook { get; set; }
        public int idIsolation { get; set; }
        public int idOfficeType { get; set; }
        public int gasType { get; set; }
        public int thermopanel { get; set; }
        public int typeHotWater { get; set; }
        public string typeHeating { get; set; }
        public int kitchenType { get; set; }
        public int constructionType { get; set; }
        public int ceilingType { get; set; }
        public int windowType { get; set; }
        public int sewerage { get; set; }
        public int waterType { get; set; }
        public int energyType { get; set; }
        public string coverageType { get; set; }
        public string disposition { get; set; }
        public int farmType { get; set; }
        public string garageAccess { get; set; }
        public string garageType { get; set; }
        public int checkIn { get; set; }
        public int checkOut { get; set; }
        public string typeOfWarehouse { get; set; }
        public int landAccess { get; set; }
        public int lotDisposition { get; set; }
        public string lotShape { get; set; }
        public int maintenanceFeeType { get; set; }
        public string propertyOwnership { get; set; }
        public bool yard { get; set; }
        public int commonExpenses { get; set; }
    }

}
